# Generated by Django 4.1.3 on 2022-11-23 22:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("title", models.TextField()),
                (
                    "price_origin",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "price_kgs",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "usd_rate",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                ("currency", models.CharField(max_length=5, null=True)),
                ("description", models.TextField(null=True)),
                ("parse_datetime", models.DateTimeField()),
                ("ad_url", models.URLField(max_length=400)),
                ("address", models.TextField(null=True)),
                ("additional", models.JSONField()),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=400), size=None
                    ),
                ),
                ("rooms", models.IntegerField(null=True)),
                (
                    "apartment_area",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "land_area",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("series", models.CharField(max_length=50, null=True)),
                ("furniture", models.CharField(max_length=50, null=True)),
                ("renovation", models.CharField(max_length=50, null=True)),
                ("pets", models.CharField(max_length=50, null=True)),
                ("seller", models.CharField(max_length=80, null=True)),
            ],
            options={
                "db_table": "ads",
                "ordering": ["parse_datetime"],
            },
        ),
    ]
